name: "Create Jira Comment"

on:
  issue_comment:
    types: ["created"]

jobs:
  create-jira-comment:
    name: "Create Jira Comment"
    uses: mParticle/mparticle-workflows/.github/workflows/issue-comment-to-jira.yml@main
    secrets: inherit
